### ISSUE TITLE
lesspipe, lessfilter incompatibility?

### ISSUE THREAD

**Issue by vvatikiotis** [itsjunetime/tdf#14]
I use latest iTerm2, latest tmux, MacOS

When I directly invoke tdf in the shell (or within tmux), pdfs are rendered just fine.

When I use lesspipe,  rendering stops and stays there. 

![image](https://github.com/user-attachments/assets/b358d819-e0d9-4d87-825c-5b39c2e2d2b3)

An additional piece of info (maybe it's of help):  When I use fzf preview, with less as the preview command (which respects the lesspipe mechanism), I get the following error:

![image](https://github.com/user-attachments/assets/55a3f05f-6bc0-4653-9c5b-7e2bcae48b02)

Also, thanks for your time, cli aficionados are forever grateful :D

**Comment by alerque** [comment]
Given that tdf renders a TUI –something that doesn't work inside `less`'s streaming text model anyway because of the expectation of directly sending control sequences without them being intercepted, filtered, etc.– that also includes special graphics protocol access to the terminal, it is unlikely that this will ever work right.

A few programs con successfully wrap TUIs: specifically terminal multiplexers. This includes `screen`, `tmux`, `zellij`, and the like that are specifically designed to intercept terminal escape sequences, translate them, perhaps adjust them to the space available in a pane or whatever, then pass them to the terminal. Also some TUIs have the ability to act as terminal multiplexers and host other TUIs: vim/neovim/emacs and others fall into this category with their ability to embed terminals in their own interfaces. They basically just have terminal multiplexing ability built in.

Less is not such a tool. It isn't even a terminal multiplexer and isn't meant to wrap TUIs, it is meant to display *data* that it can parse and navigate itself. Even if it was it would still need extra special treatment for images to work.  Even `tmux` and `zellij` which are among the better multiplexers don't have support to pass through image protocols though.

**Comment by itsjunetime** [comment]
Yeah, I'm somewhat confused as to how one would expect this to work within less - I guess `tdf` could just send the terminal-specific codes to render the images through to lesspipe if the output doesn't register as a terminal?

If you have some specific use-case and expected behavior for this, we could totally look into implementing it, but as of now I'm not certain what that would look like.

**Comment by vvatikiotis** [comment]
I guess I hadn't realized how `less` works, its streaming text model as @alerque put it. From my part I'm now considering this as a non-issue. Thanks for your answers ❤️ .

**Comment by alerque** [comment]
@vvatikiotis It sounds like what you actually want is just something that essentially `cat`s a PDF. The way `tdf` is setup it is a TUI that watches for input from the user, reads a data file, and comes up with a display state that it continuously updates on output by dumping new renderings to the terminal. The problem is `less` is also a TUI that listens to use input, reads data files, figures out a view, and updates the terminal. Given that it isn't designed to have nested TUIs (it has no way to frame an area for control by another app, no way to pass user input through, etc.) there is no practical way for it to work.

I don't even thing what you want is `tdf`, you just want something that dumps a page or pages to the terminal and leaves. You can easily rig that up with other existing tools you know. You can easily dump PDF pages to a PNG with one command and pipe that into a PNG to console image converter with another. That would be pretty easy to put in your less pipe (if it supports image protocol passthrough).

**Comment by vvatikiotis** [comment]
I ended up with something as simple as `pdftotext`, for now, till I have time to try something like dump a multiple page PDF to a single file PNG image. That would work, I guess, since the terminal use has image passthrough support.  Thanks!
