### ISSUE TITLE
Is windows supported?

### ISSUE THREAD

**Issue by fastkits** [itsjunetime/tdf#16]
Is windows supported?

**Comment by fastkits** [comment]
![image](https://github.com/user-attachments/assets/7a261550-a19a-4945-a858-f4d0570f2b8b)
![image](https://github.com/user-attachments/assets/bacc0101-6163-4339-abd2-cbf25cfad817)
![image](https://github.com/user-attachments/assets/2a8ee0c7-d241-4ea7-97cf-af8390037d3b)
![image](https://github.com/user-attachments/assets/6ca83655-0a51-4c4f-9296-f792376f73b8)
![image](https://github.com/user-attachments/assets/cf985226-267b-4710-bdd0-eeeb67ef24e6)

**Comment by itsjunetime** [comment]
At the moment, `tdf` depends on a few C libraries (such as the ones you're running into issues with) which, afaik, are not easy to install and set up on Windows (if it is even possible). I'm not sure how to install these libraries or how to make the crates that we depend on (such as poppler and glib) find these libraries on a windows system.

Because this is a more generic issue with using these libraries on windows, I'm going to close this issue and recommend you look at https://github.com/gtk-rs/gtk-rs-core or other related repositories (the one I linked can probably only help you with the gio-sys, glib-sys, and gobject-sys crates, but there are similar repos for poppler and cairo) and see if they have information which you can pull from to resolve these issues. There are probably other people who have run into the same thing and figured it out.

If you can figure out how to install these libraries and get everything building on windows, I'd appreciate if you posted a comment here with the steps you took so that future users can follow the same steps to get it working as well :)
