### ISSUE TITLE
Feature request: refresh?

### ISSUE THREAD

**Issue by pinc-h** [itsjunetime/tdf#18]
Hi June,

Awesome program! Just started using it this week. I'm generating PDFs from the command line, sometimes with just trivial changes, and running tdf in split-pane has been a game changer!

I was wondering if you could add (or maybe there's already a way) to refresh the file you have open? Especially if you've just over-written the file in another instance of terminal. Currently I'm aborting (^c) then re-running tdf.

Let me know!!

--Alex

**Comment by itsjunetime** [comment]
tdf should, by default, automatically reload the file and display its updated contents whenever the file on disk changes. This can get complicated, though, with programs that delete-and-then-write PDFs (instead of just overwriting), and it seems it also behaves weirdly with tmux (see #9).

With that in mind, could you describe what you're running into more specifically (including details about your environment) so we can figure out exactly what kind of bug it is (assuming it's not refreshing when the file changes on-disk)?

**Comment by itsjunetime** [comment]
Closing this since it is the same as #24 and that is getting more activity.
