### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by Kreijstal** [itsjunetime/tdf#26]
would it be okay to add CI for testing this project?

**Comment by itsjunetime** [comment]
Yes, I think CI would be nice to have for this project. There are currently no unit tests, but the benchmarks do act as tests, and I think it would be nice, at the very least, to run those on every push. I mainly haven't spent any time on CI yet since it doesn't seem like this project has, as of yet, attracted many other contributors besides myself and I haven't felt that I need CI just for myself. 

I also don't know if I have the time to figure that all out right now, so if you or anybody else is interested in contributing a PR to get that working, that would be very appreciated. Otherwise, I may get to this at some point in the future, but I don't expect it to be super soon.
