### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Kreijstal** [itsjunetime/tdf#28]
According to https://github.com/DMSrs/poppler-rs this repository should be GPL licensed?

**Comment by itsjunetime** [comment]
Yes, thank you for pointing that out - to clarify, we don't use that `poppler-rs`, but instead [the `poppler-rs` from the GNOME org gitlab](https://gitlab.gnome.org/World/Rust/poppler-rs). For some reason, they haven't explicitly put GPL as their license in their Cargo.toml (though that is what it has to be since `poppler` itself is GPL licensed), so I didn't notice it when I first chose a license. I'll put a PR up for that soon, but may not merge it just yet. I know that someone has put up a nix package for `tdf`, so I'd like to have the PR up for a second so that they can be aware of the change before I do it (since I think licensing is relevant to them).

**Comment by chardoncs** [comment]
https://github.com/chardoncs/kurumi/issues/1

idk but I don't think there is license violation if the bindings use MIT.

`poppler-rs` is developed by gnome, and `poppler` is developed by FreeDesktop (all Red Hat children).

Furthermore, this is the same way when gnome licenses its Rust bindings of [GTK](https://gtk-rs.org/), [Cairo](https://crates.io/crates/cairo-rs), [Pango](https://crates.io/crates/pango), [glib](https://crates.io/crates/glib), and [gio](https://crates.io/crates/gio). They use the permissive MIT rather than GPL-2.0 or later.

**Comment by Kreijstal** [comment]
@chardoncs Doesn't that mean that you can use whatever program that uses the same poppler api? but in case you link poppler, your program hast to be GPL licensed? So you have these options:
Do not use poppler.
Write something that has the same interface as poppler but is not GPL licensed.
Release code as GPL?
But I'm happy to be proven wrong.

**Comment by chardoncs** [comment]
> but in case you link poppler

Dynamically linked, no Poppler in the binary.

**Comment by itsjunetime** [comment]
I would also not consider myself an expert at licensing issues, but I think anything that does actually make use of the gtk bindings has to be licensed with GPL as well. I can't find any sort of widespread consensus that GPL doesn't apply when dynamic linking - as far as I can find, most people would agree that you have to license GPL when linking to GPL code, statically or dynamically.

Additionally, the gtk bindings state, [in the `COPYRIGHT` file in their repo](https://github.com/gtk-rs/gtk4-rs/blob/main/COPYRIGHT), that:

> This project provides interoperability with various GNOME libraries but doesn't distribute any parts of them. Distributing compiled libraries and executables that link to those libraries may be subject to terms of the GNU LGPL or other licenses. For more information check the license of each GNOME library.

The poppler library, in their `README.md`, also seem to agree:

> Please note that xpdf, and thus poppler, is licensed under the GPL, not the LGPL. Consequently, any application using poppler must also be licensed under the GPL.

I think that if we link against poppler (even if it is dynamically), we have to use GPL.

**Comment by chardoncs** [comment]
Yeah I'm still checking on this to make sure there are no legal issues (especially when you get permissive bindings with copyleft shared libraries).

Previously, I just checked license compatibility of my direct dependencies. imo if they were licensed weaker than I am, there should not be an issue. 🫠

**Comment by itsjunetime** [comment]
I just merged #30, so this repo has been relicensed.
