### ISSUE TITLE
Doesn't render

### ISSUE THREAD

**Issue by Prajwalg19** [itsjunetime/tdf#3]
I tried tdf on both gnome-terminal and alacritty
- On alacritty it doesn't render properly. Everything is pixelated. Hardly visible.
- On gnome-terminal it doesn't launch i get the following error

`Couldn't render a page: Couldn't render page: Couldn't paint Context: Invalid Matrix`

**Comment by slyunicorn** [comment]
same issue

**Comment by itsjunetime** [comment]
So the issue with alacritty is that it doesn't support image graphics (see [this pr](https://github.com/alacritty/alacritty/pull/4763)), which are necessary to make this work (as it renders pdf pages to pngs, then displays them with ratatui_image). As of right now, ratatui_image renders colors to unicode halfblocks when it can't determine what graphics protocol the current window supports, but that's obviously not very good. Unfortunately, there's no easy way to display PDFs nicely when the terminal doesn't support images. We could try to extract the text and print that out in the terminal, but that would mess up formatting, and sometimes PDFs don't even contain the text they show (e.g. it's stored as an image internally anyways), so that wouldn't work in all cases. I don't think that's an issue we can really fix; I'd just recommend using a different terminal emulator.

And the issue with gnome-terminal is the same as we're seeing in issue #1, so I'll close this in favor of that.

**Comment by lucidl** [comment]
I have the same issue in warp-terminal and lxterminal. Which terminals are working?
