### ISSUE TITLE
zsh: command not found: tdf after installation

### ISSUE THREAD

**Issue by justusaugust** [itsjunetime/tdf#33]
Hi there, great project!
Maybe I am just incompetent; however, I installed everything following the instructions in README.md, but when I try to use tdf, it fails and outputs: zsh: command not found: tdf. 
![CleanShot 2024-11-17 at 15 45 32@2x](https://github.com/user-attachments/assets/cd7f1fbf-79f5-408a-959c-a328cce24472)

**Comment by justusaugust** [comment]
on OSX btw

**Comment by alerque** [comment]
You did a build not an install. You can try `cargo install --path .` instead of `cargo build`, but whether that works will depend on if you have added Cargo's bin directory to your PATH in your shell profile.

In any case this has nothing at all to do with `tdf`, this is standard tooling and you should look at Cargo docs.

**Comment by itsjunetime** [comment]
Yes, after running `cargo build --release` you should find `tdf` at `./target/release/tdf` - since it wasn't installed to your system (it was just built, not installed), it's not in your `$PATH` yet. 

I would recommend reading some guides on understanding the `$PATH` environment variable and how that works in modern shells so that you don't run into this sort of issue again in the future. I'm going to close this since it's not an issue with tdf.
