### ISSUE TITLE
[bug] xterm - content is all fuzzy

### ISSUE THREAD

**Issue by dashingdon** [itsjunetime/tdf#4]
![image](https://github.com/itsjunetime/tdf/assets/15974333/0183efe8-9eec-4ca3-a6f5-b4e574ed03c7)

**Comment by itsjunetime** [comment]
I'm seeing this as well, on the default fedora 40 package of xterm, which say it's patch 389, which is weird since sixel should be enabled by default since patch 359 (https://invisible-island.net/xterm/xterm.log.html#xterm_359). Maybe fedora doesn't enable it? I'm not sure how to check that though. Do you know how to check if the version of xterm you're using was built with sixel enabled?

**Comment by dashingdon** [comment]
> xterm -version

xterm(379): it does not look like the version I installed from debian repo has sixel enabled. 

Found the solution [here](https://github.com/hackerb9/lsix?tab=readme-ov-file#xterm)

- run `xterm -ti vt340`

in the same source,[ here is the list](https://github.com/hackerb9/lsix?tab=readme-ov-file#sixel-compatible-terminals) of sixel enabled terminals

**Comment by itsjunetime** [comment]
Oh perfect - kinda weird you need to explicitly run it like that, but I'm glad there's a solution. That seems to make it work for me, so I'm going to close this issue.
